server.port: 8080

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/bank_cards
    username: dbuser
    password: 12345

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
      default_schema: public

  output.ansi.enabled: ALWAYS

logging.level:
  org.springframework:
    orm.jpa: INFO
    transaction: INFO
    transaction.interceptor: INFO
    orm.jpa.JpaTransactionManager: INFO
  com.example.bankcards: INFO

springdoc:
  override-with-generic-response: false # отключает автоматическую генерацию ответов из RestControllerAdvice
  default-produces-media-type: application/json
  swagger-ui.show-common-extensions: true # отображение ограничений @Min @Max и тп.
  api-docs.path: /api-docs


