server.port: 8080

spring:
  application:
    name: bank-rest
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5433}/${POSTGRES_DB:bank_cards}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:password}

  liquibase:
    change-log: classpath:db/migration/db.changelog-master.yaml

  jpa:
    hibernate.ddl-auto: none
    show-sql: false
    properties:
      hibernate.format_sql: true
      default_schema: public

  output.ansi.enabled: ALWAYS

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    org.springframework:
      orm.jpa: INFO
      transaction: INFO
      transaction.interceptor: INFO
      orm.jpa.JpaTransactionManager: INFO
    com.example.bankcards: INFO

springdoc:
  override-with-generic-response: false # отключает автоматическую генерацию ответов из RestControllerAdvice
  default-produces-media-type: application/json
  swagger-ui.show-common-extensions: true # отображение ограничений @Min @Max и тп.
  api-docs.path: /api-docs

jwt.lifetime: 30m
